version: '3'
services:
  dotnexus:
    build: 
      context: .
      dockerfile: DotNexus.App/Dockerfile
    ports:
     - "5001:80"
    network_mode: host
    depends_on:
     - tritium
  tritium:
    image: "tritium"
    hostname: "tritium"
    ports:
     - "8080"
     - "9090"
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./tao-api:/root/.TAO