FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

COPY . ./
COPY Config/appsettings.json /app/DotNexus.App/appsettings.json
WORKDIR /app/DotNexus.App
RUN dotnet publish -c Release -o out

EXPOSE 5001

FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app/DotNexus.App
COPY --from=build-env /app/DotNexus.App/out .
ENTRYPOINT ["dotnet", "DotNexus.App.dll"]